import { contracts } from "./contracts";
import type {
  AgentInvoiceRecord,
  ClientInvoiceRecord,
  RequestRecord,
  SimCard,
  Smartphone,
} from "./types";

export const currentAgent = {
  name: "Camille Duforet",
  country: "France",
  currency: "EUR" as const,
  salary: 2400,
  rolloutAdvance: 300,
};

export const agentContracts = contracts.filter((c) => c.agentName === currentAgent.name);
// -> Aurora Retail Group — France, Solene Cosmetics — France

export const agentRequests: RequestRecord[] = [
  {
    id: "req-5501",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    type: "Topup",
    status: "Submitted",
    raisedBy: "Nadia Okafor",
    createdAt: "2026-09-14T08:12:00Z",
    updatedAt: "2026-09-14T08:12:00Z",
    note: "€30 prepaid topup for the Lyon showroom demo phone.",
  },
  {
    id: "req-5502",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    type: "Repair",
    status: "In Progress",
    raisedBy: "Élise Fabron",
    assignedAgent: currentAgent.name,
    createdAt: "2026-09-12T14:05:00Z",
    updatedAt: "2026-09-14T09:30:00Z",
    note: "Cracked screen on the counter display unit, sent to repair partner.",
  },
  {
    id: "req-5503",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    type: "SIM Swap",
    status: "Submitted",
    raisedBy: "Nadia Okafor",
    createdAt: "2026-09-13T11:47:00Z",
    updatedAt: "2026-09-13T11:47:00Z",
  },
  {
    id: "req-5504",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    type: "Reboot",
    status: "Completed",
    raisedBy: "Nadia Okafor",
    assignedAgent: currentAgent.name,
    createdAt: "2026-09-10T09:00:00Z",
    updatedAt: "2026-09-10T09:20:00Z",
  },
  {
    id: "req-5505",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    type: "Provision Smartphone",
    status: "In Progress",
    raisedBy: "Élise Fabron",
    assignedAgent: currentAgent.name,
    createdAt: "2026-09-09T16:22:00Z",
    updatedAt: "2026-09-13T10:10:00Z",
    note: "Replacement unit for the retired Pixel 8 (serial ending 4471).",
  },
  {
    id: "req-5506",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    type: "Topup",
    status: "Completed",
    raisedBy: "Élise Fabron",
    assignedAgent: currentAgent.name,
    createdAt: "2026-09-02T10:00:00Z",
    updatedAt: "2026-09-02T15:40:00Z",
  },
  {
    id: "req-5507",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    type: "Provision SIM",
    status: "Cancelled",
    raisedBy: "Nadia Okafor",
    createdAt: "2026-08-29T13:00:00Z",
    updatedAt: "2026-08-30T09:00:00Z",
    note: "Duplicate of req-5501, cancelled by requester.",
  },
  {
    id: "req-5508",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    type: "Reboot",
    status: "Completed",
    raisedBy: "Élise Fabron",
    assignedAgent: currentAgent.name,
    createdAt: "2026-08-27T09:12:00Z",
    updatedAt: "2026-08-27T09:25:00Z",
  },
];

export const agentSmartphones: Smartphone[] = [
  {
    id: "phn-1",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    model: "iPhone 15",
    serial: "F2Q3-9931",
    status: "Active",
    assignedTo: "Lyon showroom",
  },
  {
    id: "phn-2",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    model: "iPhone 15",
    serial: "F2Q3-9932",
    status: "Active",
    assignedTo: "Paris flagship",
  },
  {
    id: "phn-3",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    model: "Pixel 8",
    serial: "GX8L-4471",
    status: "Retired",
    assignedTo: "Counter display — replaced",
  },
  {
    id: "phn-4",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    model: "Pixel 8a",
    serial: "GX8L-5102",
    status: "In Repair",
    assignedTo: "Counter display — Marseille",
  },
  {
    id: "phn-5",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    model: "iPhone 14",
    serial: "F1P2-2290",
    status: "Active",
    assignedTo: "Warehouse handheld",
  },
];

export const agentSimCards: SimCard[] = [
  {
    id: "sim-1",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    number: "+33 6 12 88 40 21",
    flavor: "Postpaid",
    status: "Active",
    monthlyFee: 24,
    carrier: "Orange FR",
  },
  {
    id: "sim-2",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    number: "+33 6 12 88 40 22",
    flavor: "Postpaid",
    status: "Active",
    monthlyFee: 24,
    carrier: "Orange FR",
  },
  {
    id: "sim-3",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    number: "+33 6 44 10 92 03",
    flavor: "Prepaid",
    status: "Active",
    monthlyFee: 0,
    carrier: "SFR",
  },
  {
    id: "sim-4",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    number: "+33 6 44 10 92 04",
    flavor: "Postpaid",
    status: "Active",
    monthlyFee: 18,
    carrier: "SFR",
  },
];

export const agentClientInvoices: ClientInvoiceRecord[] = [
  {
    id: "ci-aurora-sept",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    month: "September 2026",
    status: "draft",
    baseAmount: 48,
    feesAmount: 214,
    totalAmount: 262,
    currency: "EUR",
    carrierFilesAttached: 0,
  },
  {
    id: "ci-aurora-aug",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    month: "August 2026",
    status: "approved",
    baseAmount: 1840,
    feesAmount: 612.5,
    totalAmount: 2452.5,
    currency: "EUR",
    carrierFilesAttached: 2,
    sentAt: "2026-09-03T09:14:00Z",
  },
  {
    id: "ci-solene-sept",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    month: "September 2026",
    status: "draft",
    baseAmount: 18,
    feesAmount: 340,
    totalAmount: 358,
    currency: "EUR",
    carrierFilesAttached: 1,
  },
  {
    id: "ci-solene-aug",
    contractId: "ctr-solene-fr",
    contractLabel: "Solene Cosmetics — France",
    month: "August 2026",
    status: "sent",
    baseAmount: 1120,
    feesAmount: 480,
    totalAmount: 1600,
    currency: "EUR",
    carrierFilesAttached: 1,
    sentAt: "2026-09-02T11:00:00Z",
  },
];

export const myAgentInvoices: AgentInvoiceRecord[] = [
  {
    id: "ai-camille-aug",
    agentName: currentAgent.name,
    month: "August 2026",
    status: "approved",
    localSupportFees: 3120.5,
    salary: 2400,
    rolloutRepayment: -300,
    rolloutNewAdvance: 300,
    currency: "EUR",
    total: 5520.5,
    submittedAt: "2026-09-05T10:22:00Z",
  },
  {
    id: "ai-camille-jul",
    agentName: currentAgent.name,
    month: "July 2026",
    status: "paid",
    localSupportFees: 2870,
    salary: 2400,
    rolloutRepayment: 0,
    rolloutNewAdvance: 300,
    currency: "EUR",
    total: 5570,
    submittedAt: "2026-08-04T09:00:00Z",
  },
  {
    id: "ai-camille-jun",
    agentName: currentAgent.name,
    month: "June 2026",
    status: "paid",
    localSupportFees: 3040,
    salary: 2400,
    rolloutRepayment: 0,
    rolloutNewAdvance: 0,
    currency: "EUR",
    total: 5440,
    submittedAt: "2026-07-03T09:00:00Z",
  },
];

// September's invoice hasn't been started yet — used to demonstrate the
// "not started" empty state on My Invoice.
export const currentMonthLabel = "September 2026";
export const runningLocalSupportFees = agentClientInvoices
  .filter((inv) => inv.month === currentMonthLabel)
  .reduce((sum, inv) => sum + inv.totalAmount, 0);
