import { contracts } from "./contracts";
import type { ClientInvoiceRecord, RequestRecord, SimCard, Smartphone } from "./types";

export const currentClient = {
  name: "Aurora Retail Group",
  primaryContact: "Nadia Okafor",
  currentTester: "Nadia Okafor",
};

export const clientContracts = contracts.filter((c) => c.clientName === currentClient.name);
// -> Aurora Retail Group — France, Aurora Retail Group — United Kingdom

export const clientRequests: RequestRecord[] = [
  {
    id: "req-6101",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    type: "Topup",
    status: "Submitted",
    raisedBy: "Nadia Okafor",
    createdAt: "2026-09-14T08:12:00Z",
    updatedAt: "2026-09-14T08:12:00Z",
    note: "€30 prepaid topup for the Lyon showroom demo phone.",
  },
  {
    id: "req-6102",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    type: "SIM Swap",
    status: "Submitted",
    raisedBy: "Nadia Okafor",
    createdAt: "2026-09-13T11:47:00Z",
    updatedAt: "2026-09-13T11:47:00Z",
  },
  {
    id: "req-6103",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    type: "Reboot",
    status: "Completed",
    raisedBy: "Nadia Okafor",
    assignedAgent: "Camille Duforet",
    createdAt: "2026-09-10T09:00:00Z",
    updatedAt: "2026-09-10T09:20:00Z",
  },
  {
    id: "req-6104",
    contractId: "ctr-aurora-uk",
    contractLabel: "Aurora Retail Group — United Kingdom",
    type: "Repair",
    status: "In Progress",
    raisedBy: "Marcus Lee",
    assignedAgent: "Owen Whitfield",
    createdAt: "2026-09-11T15:30:00Z",
    updatedAt: "2026-09-13T10:00:00Z",
    note: "Loose SIM tray on the Manchester store handheld.",
  },
  {
    id: "req-6105",
    contractId: "ctr-aurora-uk",
    contractLabel: "Aurora Retail Group — United Kingdom",
    type: "Provision Smartphone",
    status: "Completed",
    raisedBy: "Marcus Lee",
    assignedAgent: "Owen Whitfield",
    createdAt: "2026-09-01T09:00:00Z",
    updatedAt: "2026-09-04T09:00:00Z",
  },
];

export const clientSmartphones: Smartphone[] = [
  {
    id: "phn-1",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    model: "iPhone 15",
    serial: "F2Q3-9931",
    status: "Active",
    assignedTo: "Lyon showroom",
  },
  {
    id: "phn-2",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    model: "iPhone 15",
    serial: "F2Q3-9932",
    status: "Active",
    assignedTo: "Paris flagship",
  },
  {
    id: "phn-6",
    contractId: "ctr-aurora-uk",
    contractLabel: "Aurora Retail Group — United Kingdom",
    model: "iPhone 15",
    serial: "UKQ1-1120",
    status: "Active",
    assignedTo: "Manchester store",
  },
  {
    id: "phn-7",
    contractId: "ctr-aurora-uk",
    contractLabel: "Aurora Retail Group — United Kingdom",
    model: "Galaxy S24",
    serial: "UKQ1-1121",
    status: "In Repair",
    assignedTo: "Manchester store — spare",
  },
];

export const clientSimCards: SimCard[] = [
  {
    id: "sim-1",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    number: "+33 6 12 88 40 21",
    flavor: "Postpaid",
    status: "Active",
    monthlyFee: 24,
    carrier: "Orange FR",
  },
  {
    id: "sim-2",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    number: "+33 6 12 88 40 22",
    flavor: "Postpaid",
    status: "Active",
    monthlyFee: 24,
    carrier: "Orange FR",
  },
  {
    id: "sim-6",
    contractId: "ctr-aurora-uk",
    contractLabel: "Aurora Retail Group — United Kingdom",
    number: "+44 7700 900312",
    flavor: "Postpaid",
    status: "Active",
    monthlyFee: 19,
    carrier: "Vodafone UK",
  },
];

export const clientInvoices: ClientInvoiceRecord[] = [
  {
    id: "ci-aurora-fr-sept",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    month: "September 2026",
    status: "draft",
    baseAmount: 48,
    feesAmount: 214,
    totalAmount: 262,
    currency: "EUR",
    carrierFilesAttached: 0,
  },
  {
    id: "ci-aurora-fr-aug",
    contractId: "ctr-aurora-fr",
    contractLabel: "Aurora Retail Group — France",
    month: "August 2026",
    status: "approved",
    baseAmount: 1840,
    feesAmount: 612.5,
    totalAmount: 2452.5,
    currency: "EUR",
    carrierFilesAttached: 2,
    sentAt: "2026-09-03T09:14:00Z",
  },
  {
    id: "ci-aurora-uk-aug",
    contractId: "ctr-aurora-uk",
    contractLabel: "Aurora Retail Group — United Kingdom",
    month: "August 2026",
    status: "sent",
    baseAmount: 950,
    feesAmount: 310,
    totalAmount: 1260,
    currency: "GBP",
    carrierFilesAttached: 1,
    sentAt: "2026-09-05T12:00:00Z",
  },
  {
    id: "ci-aurora-uk-jul",
    contractId: "ctr-aurora-uk",
    contractLabel: "Aurora Retail Group — United Kingdom",
    month: "July 2026",
    status: "approved",
    baseAmount: 950,
    feesAmount: 180,
    totalAmount: 1130,
    currency: "GBP",
    carrierFilesAttached: 1,
    sentAt: "2026-08-04T09:00:00Z",
  },
];
